name: "Deploy"
on:
  push:
    branches:
      - main

jobs:
  deployment:
    runs-on: "ubuntu-latest"
    environment: test
    concurrency: test
    steps:
      - uses: actions/checkout@v1

      - name: "Deploy"
        uses: "deliverybot/helm@v3"
        with:
          release: "nginx"
          namespace: "default"
          chart: "app"
          token: "${{ github.token }}"
          values: |
            name: foobar
        env:
          KUBECONFIG_FILE: "${{ secrets.KUBECONFIG }}"
